### ISSUE TITLE
StackFrame Code Support

### ISSUE THREAD

**Issue by pbrisbin** [pbrisbin/bugsnag-haskell#14]
~~Here's a probably-terrible idea...~~

We could supply a TH function that reads your project directory into an index at compile time, which you then set on settings:

```hs
, bsCodeIndex = $(whateverDoTheThing "./src")
```

We could then have a function like `BugsnagStackFrame -> BugsnagCodeIndex -> Maybe BugsnagCode` which grabs the 6 lines of source by line number, which we'd then attach to the stack frame.

**Comment by pbrisbin** [comment]
I have no idea, just seems a little unusual, doesn't it? Feels like something that'll have security or performance problems.

**Comment by jezen** [comment]
I could envision security problems if both of the following are true:
1. Stack traces are leaked to user
2. Secrets are stored in code

Aside from that, I can't say. In any case, this experimental project _may_ be useful, I'm not sure: https://hackage.haskell.org/package/error-context

**Comment by pbrisbin** [comment]
I'm now thinking this isn't too terrible an idea. It'll be fun to build, an isolated thing within the library, and 100% opt-in anyway. :+1:

**Comment by pbrisbin** [comment]
Merged. Will be in v0.0.2.0.
