### ISSUE TITLE
Upload to Stackage?

### ISSUE THREAD

**Issue by MaxGabriel** [pbrisbin/bugsnag-haskell#30]
Hi Patrick :)

If it's no trouble, would you mind adding this to Stackage? Honestly, this is really only the most trivial of convenience for me—we aren't using Stackage currently—I just use its built-in Hoogle to search for stuff. But I imagine other people would want to use it there anyway

**Comment by pbrisbin** [comment]
Thanks for the bump. PR open on `commercialhaskell/stackage`.
