### ISSUE TITLE
src/Network/Bugsnag/CodeIndex.hs: error: ‘System.FilePath.Glob’ does not export ‘glob’

### ISSUE THREAD

**Issue by juhp** [pbrisbin/bugsnag-haskell#42]
In the Stackage Nightly build:

```
> /tmp/stackage-build12/bugsnag-haskell-0.0.2.0$ dist/build/doctest/doctest

src/Network/Bugsnag/CodeIndex.hs:22:30: error:
    Module ‘System.FilePath.Glob’ does not export ‘glob’
   |
22 | import System.FilePath.Glob (glob)
   |                              ^^^^
```

**Comment by pbrisbin** [comment]
He @juhp thanks for letting me know.

I'm afraid I'm having some trouble tracking this down.  I build with nightly on CI and [it's passing for me](https://circleci.com/gh/pbrisbin/bugsnag-haskell/183). I also confirmed that [`Glob` does export that function](http://hackage.haskell.org/package/Glob-0.9.2/docs/System-FilePath-Glob.html#v:glob). This version is [in the latest nightly](https://www.stackage.org/nightly-2018-09-06/package/Glob-0.9.2), but without any module documentation. Interestingly, a [Hoogle search on that resolver](https://www.stackage.org/nightly-2018-09-06/hoogle?q=Glob) can't find anything from `Glob`, though it does find [this module](https://www.stackage.org/haddock/nightly-2018-09-06/filemanip-0.3.6.3/System-FilePath-Glob.html) from some other package I'm not using... :confused: 

Is it possible there's some other issue going on with the `Glob` package in the actual stackage-build process that's causing this?

**Comment by juhp** [comment]
I suspect rather is something with doctest dependencies in our build environment...
