### ISSUE TITLE
Cabal tarball doesn't include fixtures

### ISSUE THREAD

**Issue by MaxGabriel** [pbrisbin/bugsnag-haskell#45]
The cabal tarball doesn't include the `fixtures` directory the tests use. This causes the code index tests to fail. I ran into this when building with Nix, which downloaded the package from hackage and then ran tests, but failed on the code index tests.

To reproduce, download the tarball from https://hackage.haskell.org/package/bugsnag-haskell-0.0.2.1/bugsnag-haskell-0.0.2.1.tar.gz

**Comment by pbrisbin** [comment]
Should be fixed in v0.0.2.2. Please re-open if not.

**Comment by MaxGabriel** [comment]
Cool, thanks Pat 👍
